controller_manager:
  ros__parameters:

    update_rate: 100 # Hz
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_controller:
  ros__parameters:
    joints:
      - $(var arm_type)joint1
      - $(var arm_type)joint2
      - $(var arm_type)joint3
      - $(var arm_type)joint4
      - $(var arm_type)joint5
      - $(var arm_type)joint6
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 1.0
      $(var arm_type)joint1: { trajectory: 0.2, goal: 0.1 }
      $(var arm_type)joint2: { trajectory: 0.2, goal: 0.1 }
      $(var arm_type)joint3: { trajectory: 0.2, goal: 0.1 }
      $(var arm_type)joint4: { trajectory: 0.2, goal: 0.1 }
      $(var arm_type)joint5: { trajectory: 0.2, goal: 0.1 }
      $(var arm_type)joint6: { trajectory: 0.2, goal: 0.1 }
